/**
 * Mock data for demonstration when Supabase is not configured.
 * Replace with real Supabase data in production.
 */

import type { Property, PropertyImage, UserProfile } from "./supabase";

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "1",
    code: "IMV-1001",
    title: "Casa Alto Padrão com Piscina",
    description:
      "Espaçosa residência de alto padrão com acabamento premium. Sala de estar ampla com pé-direito duplo, cozinha gourmet equipada, área de lazer completa com piscina aquecida, churrasqueira e jardim paisagístico. Localizada em condomínio fechado com segurança 24h.",
    listing_type: "venda",
    price: 1850000,
    city: "São Paulo",
    neighborhood: "Alphaville",
    address: "Rua das Palmeiras, 450",
    zip_code: "06454-000",
    bedrooms: 4,
    bathrooms: 5,
    parking_spots: 4,
    built_area: 380,
    land_area: 600,
    property_type: "casa",
    status: "disponivel",
    featured: true,
    main_image_url:
      "https://d2xsxph8kpxj0f.cloudfront.net/310519663776255515/Y24dj4zK4qnVXuNjCoSvoL/property-modern-house-c7reL84MqtGupBTix4xFJh.webp",
    agent_id: "agent-1",
    agent_name: "Carlos Mendes",
    slug: "casa-alto-padrao-alphaville-imv-1001",
    published_at: "2024-01-15T10:00:00Z",
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    code: "IMV-1002",
    title: "Apartamento Luxo Vista Panorâmica",
    description:
      "Apartamento de alto padrão com vista panorâmica para a cidade. Acabamento com materiais nobres, piso de mármore, cozinha americana equipada, varanda gourmet. Condomínio com academia, piscina, salão de festas e concierge.",
    listing_type: "venda",
    price: 2200000,
    city: "São Paulo",
    neighborhood: "Itaim Bibi",
    address: "Av. Brigadeiro Faria Lima, 3900",
    zip_code: "04538-132",
    bedrooms: 3,
    bathrooms: 4,
    parking_spots: 3,
    built_area: 220,
    land_area: null,
    property_type: "apartamento",
    status: "disponivel",
    featured: true,
    main_image_url:
      "https://d2xsxph8kpxj0f.cloudfront.net/310519663776255515/Y24dj4zK4qnVXuNjCoSvoL/property-luxury-apt-eCNKWVqyFWyTaXxpSxTZvp.webp",
    agent_id: "agent-2",
    agent_name: "Ana Rodrigues",
    slug: "apartamento-luxo-itaim-bibi-imv-1002",
    published_at: "2024-01-20T10:00:00Z",
    created_at: "2024-01-20T10:00:00Z",
    updated_at: "2024-01-20T10:00:00Z",
  },
  {
    id: "3",
    code: "IMV-1003",
    title: "Casa Moderna em Condomínio Fechado",
    description:
      "Linda casa moderna em condomínio fechado de alto padrão. Projeto arquitetônico contemporâneo com grandes janelas, integração sala-cozinha, suíte master com closet e banheira de hidromassagem. Área de lazer privativa.",
    listing_type: "aluguel",
    price: 8500,
    city: "Campinas",
    neighborhood: "Jardim Chapadão",
    address: "Rua dos Ipês, 120",
    zip_code: "13070-000",
    bedrooms: 3,
    bathrooms: 3,
    parking_spots: 2,
    built_area: 280,
    land_area: 450,
    property_type: "casa",
    status: "disponivel",
    featured: true,
    main_image_url:
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
    agent_id: "agent-1",
    agent_name: "Carlos Mendes",
    slug: "casa-moderna-campinas-imv-1003",
    published_at: "2024-02-01T10:00:00Z",
    created_at: "2024-02-01T10:00:00Z",
    updated_at: "2024-02-01T10:00:00Z",
  },
  {
    id: "4",
    code: "IMV-1004",
    title: "Apartamento Studio Moderno",
    description:
      "Studio moderno e funcional, ideal para jovens profissionais. Localização privilegiada próximo ao metrô, comércio e serviços. Acabamento de qualidade, varanda, área de serviço. Condomínio com academia e rooftop.",
    listing_type: "aluguel",
    price: 3200,
    city: "São Paulo",
    neighborhood: "Vila Madalena",
    address: "Rua Aspicuelta, 55",
    zip_code: "05433-010",
    bedrooms: 1,
    bathrooms: 1,
    parking_spots: 1,
    built_area: 45,
    land_area: null,
    property_type: "apartamento",
    status: "reservado",
    featured: false,
    main_image_url:
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
    agent_id: "agent-2",
    agent_name: "Ana Rodrigues",
    slug: "studio-vila-madalena-imv-1004",
    published_at: "2024-02-05T10:00:00Z",
    created_at: "2024-02-05T10:00:00Z",
    updated_at: "2024-02-05T10:00:00Z",
  },
  {
    id: "5",
    code: "IMV-1005",
    title: "Terreno Comercial em Área Nobre",
    description:
      "Excelente terreno em área nobre com alto potencial construtivo. Localização estratégica em avenida principal, próximo a grandes centros comerciais. Documentação em ordem, pronto para construção.",
    listing_type: "venda",
    price: 950000,
    city: "São Paulo",
    neighborhood: "Moema",
    address: "Av. Ibirapuera, 2000",
    zip_code: "04029-000",
    bedrooms: null,
    bathrooms: null,
    parking_spots: null,
    built_area: null,
    land_area: 800,
    property_type: "terreno",
    status: "em_negociacao",
    featured: false,
    main_image_url:
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
    agent_id: "agent-1",
    agent_name: "Carlos Mendes",
    slug: "terreno-moema-imv-1005",
    published_at: "2024-02-10T10:00:00Z",
    created_at: "2024-02-10T10:00:00Z",
    updated_at: "2024-02-10T10:00:00Z",
  },
  {
    id: "6",
    code: "IMV-1006",
    title: "Cobertura Duplex com Piscina Privativa",
    description:
      "Cobertura duplex exclusiva com piscina privativa e vista 360° para a cidade. Dois andares de puro luxo com materiais importados, home theater, adega climatizada e área gourmet completa. Um imóvel único.",
    listing_type: "venda",
    price: 4500000,
    city: "São Paulo",
    neighborhood: "Jardins",
    address: "Rua Oscar Freire, 800",
    zip_code: "01426-000",
    bedrooms: 5,
    bathrooms: 6,
    parking_spots: 5,
    built_area: 520,
    land_area: null,
    property_type: "apartamento",
    status: "disponivel",
    featured: true,
    main_image_url:
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
    agent_id: "agent-2",
    agent_name: "Ana Rodrigues",
    slug: "cobertura-duplex-jardins-imv-1006",
    published_at: "2024-02-15T10:00:00Z",
    created_at: "2024-02-15T10:00:00Z",
    updated_at: "2024-02-15T10:00:00Z",
  },
];

export const MOCK_TESTIMONIALS = [
  {
    id: 1,
    name: "Roberto Almeida",
    role: "Empresário",
    text: "A ImóvelPrime superou todas as minhas expectativas. Em menos de 30 dias encontraram o imóvel perfeito para minha família. Atendimento excepcional e total transparência em todo o processo.",
    rating: 5,
    avatar: "RA",
  },
  {
    id: 2,
    name: "Fernanda Costa",
    role: "Médica",
    text: "Profissionalismo e agilidade definem a equipe da ImóvelPrime. Alugaram meu apartamento em tempo recorde com um inquilino de excelente perfil. Recomendo sem hesitar.",
    rating: 5,
    avatar: "FC",
  },
  {
    id: 3,
    name: "Marcelo Santos",
    role: "Investidor",
    text: "Já realizei três transações com a ImóvelPrime e em todas tive a mesma qualidade de atendimento. Corretores experientes, documentação impecável e suporte jurídico completo.",
    rating: 5,
    avatar: "MS",
  },
];

export const MOCK_AGENTS: UserProfile[] = [
  {
    id: "agent-1",
    full_name: "Carlos Mendes",
    email: "carlos@imovelprime.com.br",
    phone: "(11) 98765-4321",
    role: "corretor",
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2023-01-01T00:00:00Z",
  },
  {
    id: "agent-2",
    full_name: "Ana Rodrigues",
    email: "ana@imovelprime.com.br",
    phone: "(11) 97654-3210",
    role: "corretor",
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2023-01-01T00:00:00Z",
  },
];

export const MOCK_PROPERTY_IMAGES: Record<string, PropertyImage[]> = {
  "1": [
    {
      id: "img-1-1",
      property_id: "1",
      url: "https://d2xsxph8kpxj0f.cloudfront.net/310519663776255515/Y24dj4zK4qnVXuNjCoSvoL/property-modern-house-c7reL84MqtGupBTix4xFJh.webp",
      is_main: true,
      order_index: 0,
      created_at: "2024-01-15T10:00:00Z",
    },
    {
      id: "img-1-2",
      property_id: "1",
      url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
      is_main: false,
      order_index: 1,
      created_at: "2024-01-15T10:00:00Z",
    },
    {
      id: "img-1-3",
      property_id: "1",
      url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80",
      is_main: false,
      order_index: 2,
      created_at: "2024-01-15T10:00:00Z",
    },
  ],
  "2": [
    {
      id: "img-2-1",
      property_id: "2",
      url: "https://d2xsxph8kpxj0f.cloudfront.net/310519663776255515/Y24dj4zK4qnVXuNjCoSvoL/property-luxury-apt-eCNKWVqyFWyTaXxpSxTZvp.webp",
      is_main: true,
      order_index: 0,
      created_at: "2024-01-20T10:00:00Z",
    },
    {
      id: "img-2-2",
      property_id: "2",
      url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
      is_main: false,
      order_index: 1,
      created_at: "2024-01-20T10:00:00Z",
    },
  ],
};
